import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Check, FileDown, Edit3 } from 'lucide-react'
import { jsPDF } from 'jspdf'

export default function OrderSummary({ isOpen, onClose, onConfirm, data }) {
   const [isSuccess, setIsSuccess] = useState(false);

   // Reset success state when modal opens
   useEffect(() => {
      if (isOpen) setIsSuccess(false);
   }, [isOpen]);

   if (!isOpen || !data) return null;

   const {
      color, strawType, endType, length, diameter, wrapperType,
      numMasterCartons, qtyPerInnerBox, innerBoxesPerCarton, totalQty, comments
   } = data;

   // Format numbers for display
   const fmt = (n) => new Intl.NumberFormat('en-US').format(n);

   const handleConfirmAction = () => {
      setIsSuccess(true);
      // Wait for animation then confirm and clear
      setTimeout(() => {
         onConfirm();
      }, 2000);
   };

   const handleDownloadPDF = () => {
      const doc = new jsPDF();

      // --- PDF STYLING ---
      const lineHeight = 10;
      let y = 20;

      // Header
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text("Straw Order Configuration", 20, y);
      y += 15;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, y);
      y += 20;

      // Section: Product Details
      doc.setFillColor(240, 240, 240);
      doc.rect(20, y - 6, 170, 10, 'F');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text("Product Details", 25, y);
      y += 15;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);

      const details = [
         [`Color`, color],
         [`Straw Type`, strawType],
         [`End Type`, endType],
         [`Length`, `${length} mm`],
         [`Diameter`, `${diameter} mm`],
         [`Wrapper`, wrapperType],
      ];

      details.forEach(([label, value]) => {
         doc.setFont('helvetica', 'bold');
         doc.text(`${label}:`, 30, y);
         doc.setFont('helvetica', 'normal');
         doc.text(`${value}`, 80, y);
         y += lineHeight;
      });

      if (comments) {
         y += 5;
         doc.setFont('helvetica', 'bold');
         doc.text("Comments:", 30, y);
         y += 7;
         doc.setFont('helvetica', 'normal');
         // Split text to fit width
         const splitComments = doc.splitTextToSize(comments, 150);
         doc.text(splitComments, 30, y);
         y += (splitComments.length * 7) + 5;
      }

      y += 10;

      // Section: Quantity Breakdown
      doc.setFillColor(240, 240, 240);
      doc.rect(20, y - 6, 170, 10, 'F');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text("Quantity Breakdown", 25, y);
      y += 15;

      const quantities = [
         [`Master Cartons`, fmt(numMasterCartons)],
         [`Inner Boxes / Carton`, fmt(innerBoxesPerCarton)],
         [`Qty / Inner Box`, fmt(qtyPerInnerBox)],
      ];

      doc.setFontSize(11);
      quantities.forEach(([label, value]) => {
         doc.text(`${label}:`, 30, y);
         doc.text(`${value}`, 150, y, { align: 'right' });
         y += lineHeight;
      });

      // Total Line
      y += 5;
      doc.setLineWidth(0.5);
      doc.line(30, y, 180, y);
      y += 10;
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text("Total Quantity:", 30, y);
      doc.text(`${fmt(totalQty)} Straws`, 180, y, { align: 'right' });

      // Footer
      y = 280;
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text("Generated by B2B Straw Configurator", 105, y, { align: 'center' });

      doc.save('straw-order-config.pdf');
   };

   return (
      <AnimatePresence>
         {isOpen && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
               {/* Backdrop */}
               <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  onClick={onClose}
                  className="absolute inset-0 bg-black/40 backdrop-blur-md"
               />

               {/* Modal Card */}
               <motion.div
                  initial={{ scale: 0.95, opacity: 0, y: 20 }}
                  animate={{ scale: 1, opacity: 1, y: 0 }}
                  exit={{ scale: 0.95, opacity: 0, y: 20 }}
                  className="relative w-full max-w-2xl bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
               >
                  {/* Header */}
                  <div className="bg-gray-50 border-b p-6 flex items-center justify-between">
                     <div>
                        <h2 className="text-2xl font-bold text-gray-900">Review Your Order</h2>
                        <p className="text-sm text-gray-500">Please verify standard configuration before exporting.</p>
                     </div>
                     <button
                        onClick={onClose}
                        className="p-2 rounded-full hover:bg-gray-200 text-gray-500 transition-colors"
                     >
                        <X size={24} />
                     </button>
                  </div>

                  {/* Content - Scrollable */}
                  <div className="p-6 sm:p-8 overflow-y-auto custom-scrollbar space-y-8">

                     {/* 2-Column Grid */}
                     <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                        {/* Config Details */}
                        <div className="space-y-4">
                           <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2 border-b pb-1">Specifications</h3>
                           <div className="space-y-3">
                              <Row label="Straw Type" value={strawType} />
                              <Row label="End Type" value={endType} />
                              <Row label="Dimensions" value={`${length}mm x ${diameter}mm`} />

                              <div className="flex justify-between items-center py-1">
                                 <span className="text-sm text-gray-600 font-medium">Color</span>
                                 <div className="flex items-center gap-2">
                                    <span className="text-sm font-bold text-gray-900">{color}</span>
                                    <div className="w-4 h-4 rounded-full border border-gray-200 shadow-sm" style={{ backgroundColor: color }} />
                                 </div>
                              </div>

                              <Row label="Wrapper" value={wrapperType} highlight={wrapperType !== 'Unwrapped'} />
                           </div>

                           {comments && (
                              <div className="mt-4 p-3 bg-yellow-50 rounded-lg border border-yellow-100 text-sm text-yellow-800">
                                 <span className="font-bold block mb-1 text-xs uppercase opacity-70">Comments</span>
                                 "{comments}"
                              </div>
                           )}
                        </div>

                        {/* Quantity Breakdown */}
                        <div className="space-y-4">
                           <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2 border-b pb-1">Volume</h3>
                           <div className="space-y-3 bg-gray-50 p-4 rounded-xl border border-gray-100">
                              <Row label="Master Cartons" value={fmt(numMasterCartons)} bold />
                              <Row label="Inner Boxes / Ctn" value={fmt(innerBoxesPerCarton)} />
                              <Row label="Qty / Inner Box" value={fmt(qtyPerInnerBox)} />

                              <div className="border-t border-gray-200 my-2 pt-2 flex justify-between items-baseline">
                                 <span className="text-sm font-bold text-gray-600">Total Quantity</span>
                                 <span className="text-2xl font-extrabold text-blue-600">{fmt(totalQty)}</span>
                              </div>
                           </div>
                        </div>
                     </div>

                  </div>

                  {/* Footer Actions */}
                  <div className={`p-6 border-t bg-gray-50 flex flex-col sm:flex-row gap-3 justify-end transition-opacity duration-300 ${isSuccess ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}>

                     <button
                        onClick={onClose}
                        className="px-6 py-3 rounded-xl border border-gray-300 font-bold text-gray-700 hover:bg-white hover:border-gray-400 transition-all flex items-center justify-center gap-2"
                     >
                        <Edit3 size={18} />
                        Edit Config
                     </button>

                     <button
                        onClick={handleDownloadPDF}
                        className="px-6 py-3 rounded-xl bg-blue-600 text-white font-bold shadow-lg hover:bg-blue-700 hover:shadow-blue-500/30 transition-all flex items-center justify-center gap-2"
                     >
                        <FileDown size={20} />
                        Download PDF
                     </button>

                     <button
                        onClick={handleConfirmAction}
                        className="px-6 py-3 rounded-xl bg-green-600 text-white font-bold shadow-lg hover:bg-green-700 hover:shadow-green-500/30 transition-all flex items-center justify-center gap-2"
                     >
                        <Check size={20} />
                        Confirm & Clear
                     </button>
                  </div>

                  {/* Success Overlay */}
                  <AnimatePresence>
                     {isSuccess && (
                        <motion.div
                           initial={{ opacity: 0 }}
                           animate={{ opacity: 1 }}
                           className="absolute inset-0 bg-white/90 backdrop-blur-sm z-50 flex flex-col items-center justify-center"
                        >
                           <motion.div
                              initial={{ scale: 0, rotate: -45 }}
                              animate={{ scale: 1, rotate: 0 }}
                              transition={{
                                 type: "spring",
                                 stiffness: 260,
                                 damping: 20,
                                 delay: 0.1
                              }}
                              className="w-24 h-24 bg-green-500 rounded-full flex items-center justify-center text-white shadow-2xl shadow-green-500/40 mb-6"
                           >
                              <Check size={48} strokeWidth={4} />
                           </motion.div>
                           <motion.h3
                              initial={{ y: 20, opacity: 0 }}
                              animate={{ y: 0, opacity: 1 }}
                              transition={{ delay: 0.3 }}
                              className="text-2xl font-black text-gray-900"
                           >
                              Order Confirmed!
                           </motion.h3>
                           <motion.p
                              initial={{ y: 10, opacity: 0 }}
                              animate={{ y: 0, opacity: 1 }}
                              transition={{ delay: 0.4 }}
                              className="text-gray-500 mt-2"
                           >
                              Clearing configuration...
                           </motion.p>
                        </motion.div>
                     )}
                  </AnimatePresence>


               </motion.div>
            </div>
         )}
      </AnimatePresence>
   )
}

const Row = ({ label, value, bold = false, highlight = false }) => (
   <div className="flex justify-between items-center py-1">
      <span className="text-sm text-gray-600 font-medium">{label}</span>
      <span className={`text-sm ${bold ? 'font-bold text-gray-900' : 'text-gray-900'} ${highlight ? 'text-blue-600 font-bold' : ''}`}>
         {value}
      </span>
   </div>
)
