import React from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Check, Download, X } from 'lucide-react'
import jsPDF from 'jspdf'

export const OrderSummary = ({
  config,
  isOpen,
  onClose,
  onConfirm
}) => {
  const totalQty = (Number(config.qtyPerBox) || 0) * (Number(config.boxesPerCarton) || 0)

  const handleDownload = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20

    // -- Header --
    doc.setFontSize(22)
    doc.setFont("helvetica", "bold")
    doc.text("STRAW CONFIGURATION ORDER", margin, 30)

    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(100)
    doc.text(`Date: ${new Date().toLocaleDateString()}  |  Time: ${new Date().toLocaleTimeString()}`, margin, 38)
    
    // -- Divider Line --
    doc.setDrawColor(200)
    doc.line(margin, 45, pageWidth - margin, 45)

    // -- Section Title: Specifications --
    let yPos = 60
    doc.setFontSize(14)
    doc.setTextColor(0) // Black
    doc.setFont("helvetica", "bold")
    doc.text("Product Specifications", margin, yPos)
    
    yPos += 10
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")

    const specs = [
      { label: "Straw Type", value: config.strawType },
      { label: "Color (Hex)", value: config.config }, // Fix: variable is config.color not config.config
      { label: "End Type", value: config.endType },
      { label: "Wrapping", value: config.wrapped },
      { label: "Dimensions", value: `${config.length}mm (L) x ${config.diameter} (D)` },
    ]

    // Correction for the variable access in the loop below
    const data = [
      ["Straw Type", config.strawType],
      ["Color", config.color.toUpperCase()],
      ["End Type", config.endType],
      ["Wrapping", config.wrapped],
      ["Dimensions", `${config.length}mm x ${config.diameter}`]
    ]

    data.forEach(([label, value]) => {
      doc.setFont("helvetica", "bold")
      doc.text(`${label}:`, margin, yPos)
      doc.setFont("helvetica", "normal")
      doc.text(value, margin + 40, yPos)
      yPos += 8
    })

    // -- Section Title: Order Details --
    yPos += 10
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Order Quantity", margin, yPos)

    yPos += 10
    doc.setFontSize(11)
    
    const qtyData = [
      ["Qty Per Inner Box", config.qtyPerBox.toString()],
      ["Inner Boxes/Carton", config.boxesPerCarton.toString()],
    ]

    qtyData.forEach(([label, value]) => {
      doc.setFont("helvetica", "bold")
      doc.text(`${label}:`, margin, yPos)
      doc.setFont("helvetica", "normal")
      doc.text(value, margin + 45, yPos)
      yPos += 8
    })

    // -- Total Highlight --
    yPos += 5
    doc.setFillColor(245, 245, 245) // Light gray background
    doc.roundedRect(margin, yPos - 5, pageWidth - (margin * 2), 16, 2, 2, 'F')
    
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.text("TOTAL ORDER QUANTITY:", margin + 5, yPos + 6)
    doc.text(`${totalQty.toLocaleString()} STRAWS`, pageWidth - margin - 5, yPos + 6, { align: "right" })

    // -- Comments --
    if (config.comments) {
      yPos += 25
      doc.setFontSize(14)
      doc.setTextColor(0)
      doc.text("Additional Comments", margin, yPos)
      
      yPos += 8
      doc.setFontSize(10)
      doc.setFont("helvetica", "italic")
      doc.setTextColor(60)
      
      const splitComments = doc.splitTextToSize(config.comments, pageWidth - (margin * 2))
      doc.text(splitComments, margin, yPos)
    }

    // -- Footer --
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Generated by 3D Straw Configurator", pageWidth / 2, pageHeight - 10, { align: "center" })

    doc.save(`straw-order-${Date.now()}.pdf`)
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
          onClick={onClose}
        >
          <motion.div 
            initial={{ scale: 0.9, opacity: 0 }} 
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
            className="bg-white rounded-lg shadow-2xl max-w-md w-full overflow-hidden"
            onClick={(e) => e.stopPropagation()}
          >
             <div className="p-8">
                <div className="mx-auto w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-6">
                   <Check className="w-8 h-8 text-green-600" />
                </div>
                
                <h2 className="text-2xl font-bold text-center text-gray-900 mb-6">Order Summary</h2>

                <div className="space-y-3 text-sm text-gray-600 bg-gray-50 p-6 rounded-lg mb-6">
                   <div className="flex justify-between"><span>Type:</span> <span className="font-bold text-gray-900">{config.strawType}</span></div>
                   <div className="flex justify-between"><span>Color:</span> <span className="font-bold text-gray-900 truncate max-w-[150px]">{config.color}</span></div>
                   <div className="flex justify-between"><span>Wrapped:</span> <span className="font-bold text-gray-900">{config.wrapped}</span></div>
                   <div className="flex justify-between"><span>Size:</span> <span className="font-bold text-gray-900">{config.length}mm x {config.diameter}</span></div>
                   <div className="flex justify-between border-t border-gray-200 pt-2 mt-2">
                      <span>Total Quantity:</span> 
                      <span className="font-bold text-gray-900 text-base">{totalQty.toLocaleString()}</span>
                   </div>
                   {config.comments && (
                      <div className="pt-2 border-t border-gray-200 mt-2">
                         <span className="block text-xs font-bold mb-1 text-gray-500">Comments:</span>
                         <p className="text-xs italic text-gray-700">{config.comments}</p>
                      </div>
                   )}
                </div>

                <div className="space-y-3">
                   <button 
                      onClick={onConfirm}
                      className="w-full py-4 bg-black text-white font-bold uppercase tracking-wider rounded hover:bg-gray-800 shadow-lg transition-all flex items-center justify-center gap-2"
                   >
                      Confirm & Reset
                   </button>
                   
                   <div className="grid grid-cols-2 gap-3">
                      <button 
                         onClick={handleDownload}
                         className="py-3 px-4 border border-gray-200 rounded font-bold text-gray-600 hover:bg-gray-50 hover:text-gray-900 transition-colors flex items-center justify-center gap-2 text-sm"
                      >
                         <Download size={16} /> Download PDF
                      </button>
                      <button 
                         onClick={onClose}
                         className="py-3 px-4 border border-gray-200 rounded font-bold text-gray-600 hover:bg-gray-50 hover:text-gray-900 transition-colors text-sm"
                      >
                         Close
                      </button>
                   </div>
                </div>
             </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
